name: DynamicManhunt
version: '1.0'
main: me.logmilo.dynamicManhunt.DynamicManhunt
api-version: '1.21'
description: A dynamic Manhunt plugin with unique mechanics and challenges.
author: logmilo
commands:
  manhunt:
    description: Manage the Manhunt game
    usage: /<command> <start|stop>
  leaverunner:
    description: Leave the Runner role
    usage: /<command>
  checkhunters:
    description: Check the current number of hunters
    usage: /<command>
  checkrunners:
    description: Check the current number of runners
    usage: /<command>
  listplayers:
    description: Lists current runners and hunters


